server:
  port: 8080

spring:
  application:
    name: courseMicroservices
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/courseMicroservices?allowPublicRetrieval=true&sslMode=DISABLED
    username: root
    password: my-secret-pw
